# -*- coding: utf-8 -*-
"""Matrixs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KmYjboDm5tA-ycA22754pupulAFE0_ya

1. Menggunakan Library Numpy
"""

import numpy as np

matrix1 = [[1, -1, 2], [0, 3, 4]]
matrix2 = [[2, -1, 5], [7, 1, 4]]

res = np.array(matrix1) + np.array(matrix2)

print(f"Hasil matrix:\n{res}")

"""1. Menggunakan Library Sympy"""

from sympy import Matrix

matrix1 = [[1, -1, 2], [0, 3, 4]]
matrix2 = [[2, -1, 5], [7, 1, 4]]

res = Matrix(matrix1) + Matrix(matrix2)

print(f"Hasil matrix:\n{res}")

"""2. Menggunakan Library Numpy"""

import numpy as np

group1 = [
    [22, 15, 14, 23],
    [50, 62, 21, 30],
    [53, 80, 32, 40]
]

group2 = [
    [20, 38, 15, 40],
    [18, 12, 17, 80],
    [81, 47, 52, 18]
]

total = np.matrix(group1) + np.matrix(group2)

kel1 = total[0][0]
kel2 = total[1][0]
kel3 = total[2][0]

print(f"Hasil keseluruhan:\n{total}\n")
print(f"Hasil kelompok 1:\n{kel1}\n")
print(f"Hasil kelompok 2:\n{kel2}\n")
print(f"Hasil kelompok 3:\n{kel3}\n")

"""2. Menggunakan Library Sympy"""

from sympy import Matrix

group1 = [
    [22, 15, 14, 23],
    [50, 62, 21, 30],
    [53, 80, 32, 40]
]

group2 = [
    [20, 38, 15, 40],
    [18, 12, 17, 80],
    [81, 47, 52, 18]
]

total = Matrix(group1) + Matrix(group2)

kel1 = []
kel2 = []
kel3 = []

for i in range(len(total) - 8):
  kel1.append(total[i])

for i in range(len(total) - 8):
  kel2.append(total[i + 4])

for i in range(len(total) - 8):
  kel3.append(total[i + 8])

print(f"Hasil keseluruhan:\n{total}\n")
print(f"Hasil kelompok 1:\n{kel1}\n")
print(f"Hasil kelompok 2:\n{kel2}\n")
print(f"Hasil kelompok 3:\n{kel3}\n")